name: medio_ambiente
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  video_player: ^2.5.0
  provider: ^6.1.1
  youtube_player_flutter: ^8.1.2

  google_maps_flutter: ^2.6.1         # Mapa y markers
  geolocator: ^12.0.0                 # Posición actual
  geocoding: ^3.0.0                   # Buscar direcciones por coordenadas
  flutter_svg: ^2.0.9                 # Iconos SVG para categorías
  flutter_dotenv: ^5.1.0              # API keys .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
